### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by 1kdani** [PlaceholderAPI/PlaceholderAPI#1021]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Hi! Every time when I start my server, I get this error. Does anyone know, how to fix it?

My server version is: 1.19.3

### Expected Behaviour

I'm getting errors every server start.

### How to Reproduce

I've tried everything. Another versions...ect. Nothing worked

My plugins:
![image](https://github.com/PlaceholderAPI/PlaceholderAPI/assets/130190432/508c22af-6dac-4ab5-9740-7e504ee1e1d7)

### `/papi dump` Output

https://paste.helpch.at/galedizoqi

### Console Log

https://paste.helpch.at/ugeginuwer.md

### Errors

https://paste.helpch.at/ugeginuwer.md

**Comment by BlitzOffline** [comment]
Hello. This issue seems to be related to the Server Expansion you have installed on your server: https://api.extendedclip.com/expansions/server/. This is not related to PlaceholderAPI the plugin but with one of the expansions. I suggest you open an issue on this repository: https://github.com/PlaceholderAPI/Server-Expansion/
