### ISSUE TITLE
Papi variables still display the original variable name in the scoreboard and menu, not the variable content.

### ISSUE THREAD

**Issue by wuyf2011** [PlaceholderAPI/PlaceholderAPI#1075]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin/Server Incompatability

### What happens?

Any papi variable will be output as %xxx% in the menu or scoreboard, not the variable content, e.g. %player_name%, and I tried using {xxx} but it still doesn't work.

### Expected Behaviour

It should output the contents of the variable itself, e.g. %player_name% should be output as wuyf, not the original string.

### How to Reproduce

Open a menu or scoreboard with a papi variable, e.g. this scoreboard has a %player_name% in it, and it shows it just like that, and I want it to show the player's name

### `/papi dump` Output

https://paste.helpch.at/osunegahiq

**Comment by Andre601** [comment]
Your issue is explained in [the FAQ of the Wiki](https://wiki.placeholderapi.com/faq/#it-only-shows-placeholder-and-not-the-variable).

In particular are there two possible causes for you:

- The expansion is not installed (in your case the Player Expansion is not present, despite you using `%player_name%`)
- The plugin you use placeholders in may not support PAPI. Double-check that this is the case.

Either way, this is not a PAPI bug. So I close this issue.
