### ISSUE TITLE
Reload break basic expansion

### ISSUE THREAD

**Issue by Elikill58** [PlaceholderAPI/PlaceholderAPI#1086]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

After doing `/papi reload`, some placeholders no longer works

### Expected Behaviour

Works fine after papi reload

### How to Reproduce

1 Use code as explained in the wiki, like:
```java
if (pm.isPluginEnabled("PlaceholderAPI")) {
	new PlaceholderAPISupport().register();
	getLogger().info("Loaded PlaceholderAPI support.");
}
```
2. On the console, do `/papi parse <pseudo> %myplugin_placeholders%` and see the result
3. Do `/papi reload`
4. Do AGAIN `/papi parse <pseudo> %myplugin_placeholders%` and see the placeholder not beeing replaced

### `/papi dump` Output

https://paste.helpch.at/esirakucip

### Additional Info

No error, well found expansion on server start/restart

**Comment by Andre601** [comment]
Did you make sure to set your expansion to be persistent, [as shown in the wiki too?](https://wiki.placeholderapi.com/developers/creating-a-placeholderexpansion/#full-example-internal)

**Comment by Elikill58** [comment]
Oh, I didn’t see this. I understand, but for le it’s an unexpected behavior as I think this should be on true by default. Why placeholders would not be back after reload ? That’s not logical to me

**Comment by Andre601** [comment]
This behaviour isn't really unexpected. It's how PlaceholderAPI has always worked.

When you perform a reload is PlaceholderAPI not just reloading configs, but instead reloads expansions too.
This means it unloads them and then loads them again. The issue with internal expansions is, that PlaceholderAPI has no way of knowing from where they are. External expansions can be reloaded, because they are always at the same expected location: The `expansions` folder of PlaceholderAPI.
But internal ones could be anywhere, and accessing them would be extremely difficult, especially now with paper having stricter class access which iirc prevent plugins now from accessing other non-dependency's internal classes.

So the `persist()` is effectively a workaround for this issue. It tells PlaceholderAPI to not unload the expansion during its reload. This, of course, has the downside that it can't simply be updated by a swap of the jar and reload of PlaceholderAPI.

Also, once #1071 is merged will Expansion devs of internal expansions no longer need to override the `persist()` method (unless they want to keep backwards compat), as PlaceholderAPI would now have a different main way of checking an expansion to be internal, making cases like yours no longer a problem.

Also, since the missing override was your issue will I close this issue.

**Comment by Elikill58** [comment]
Thanks for all explainations.

Why don't add a second way to register it like `PlaceholderAPI.register(() -> new MyExpansion());` that would help you to load new one when you want

**Comment by Andre601** [comment]
As I mentioned before already, with #1071 being merged would it be easier for PlaceholderAPI to distinguish internal from external expansions without the need of the expansion dev to override a specific method.
So your idea would be somewhat redundant. And I am not sure if it would even work well...
