### ISSUE TITLE
CheckItem download command error

### ISSUE THREAD

**Issue by haer0248** [PlaceholderAPI/PlaceholderAPI#121]
Issue

> Download command error in wiki

Expected behaviour

> **/papi ecloud download CheckItem**

Actual behaviour

> **/papi ecloud CheckItem**

How to reproduce

> none

Version

> Now wiki page

**Comment by Funny-cube** [comment]
Please provide more information,

### Issue
> What is the issue? Describe it like you would tell a friend.

### Expected behaviour
> What should PlaceholderAPI do?

### Actual behaviour
> What does PlaceholderAPI actually do?

### How to reproduce
> What steps did you made, to get this bug?

### Version
> Version of Spigot and PlaceholderAPI

**Comment by Andre601** [comment]
[expansion]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#checkitem

@Funny-cube He means that the command listed for the [CheckItem-expansion][expansion] is wrong.
It shows `/papi ecloud CheckItem` instead of `/papi ecloud download CheckItem`

Also as an additional note is the CheckItem-expansion not listed in the navigation on the main wiki-page and the sidebar.

![image](https://user-images.githubusercontent.com/11576465/58792856-45709a80-85f5-11e9-8ef5-55be7a178ab6.png)

**Comment by Funny-cube** [comment]
Good spotting, both fixed up!

**Comment by haer0248** [comment]
@Andre601 thanks for your help!
My english is very poor so i can't understand ;(
