### ISSUE TITLE
Update Jobs placeholders

### ISSUE THREAD

**Issue by montlikadani** [PlaceholderAPI/PlaceholderAPI#152]
### Type
> What kind of request is this? (Multiple selections possible)
- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
* [x] Other: We need to change the code or create a new repository to use the placeholders for the latest version of Jobs.

### Info
> What is the change?  

Currently, [these old placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#jobs-reborn) do not support the latest ones that are included in Jobs. The new placeholders are: https://github.com/Zrips/Jobs/wiki/Placeholders

I don't know if we should create a new repository that contains the placeholders for Jobs and will add them to the Jobs developers if there is a new one coming or PlaceholderAPI will implements?

**Comment by aBo0oDyy** [comment]
Just checked Jobs Reborn source code, it the placeholders built into the plugin itself, So i unverified Jobs expansion in the [eCloud](https://api.extendedclip.com/expansions/jobs/) so users won't be able to download it using the download command and they use the placeholders from the plugin itself.
I also updated the placeholders in the [wiki](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#jobs-reborn).

Thank you for letting us know 😄

**Comment by montlikadani** [comment]
@aBo0oDyy No, when we use a registered Jobs placeholder in another plugin, it does not work properly because PAPI does not use the latest Jobs which created new placeholders and thus do not work for many users and therefore we get a lot of questions why it doesn't work when PAPI is installed and checked in `/papi parse me %jobsr_user_points%` to see if the placeholder is working or not and has not been replaced. This should be addressed by creating repositories for each plugin where the placeholders are not working properly and inserting placeholders from the plugin into the PAPI.

**Comment by aBo0oDyy** [comment]
> PAPI does not use the latest Jobs

PAPI doesn't use Jobs anyways. If you're talking about [Jobs Expansion](https://api.extendedclip.com/expansions/jobs/), as i said I've unverified so people don't download it and use Jobs placeholder from the [built-in expansion](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/Placeholders/NewPlaceholderAPIHook.java) in Jobs plugin instead.

To add your plugin's placeholders into PAPI you have two ways:
1. Create an external expansion. (Another jar to add the placeholder).
2. Hook into PAPI using an inner class in your plugin. (One jar (which is your plugin) to that adds the placeholders and the plugin itself).

And since Jobs now have an inner class in the plugin's jar (the second way of adding placeholders into PAPI), the [Jobs Expansion](https://api.extendedclip.com/expansions/jobs/) in the eCloud is NOT necessary anymore, and having it will cause confusion to users, So that't why I've unverified it.

**Comment by aBo0oDyy** [comment]
Another thing i forgot to mention,
If a PAPI placeholder didn't work in another plugin BUT its working using the parse command `/papi parse me %PlaceholderHere%`, it means the the issue from the plugin you're using the placeholder in and not PAPI's issue.

And always, if you want to try if a placeholder is working or not, you have to use PAPI's parse command.
