### ISSUE TITLE
/papi reload 

### ISSUE THREAD

**Issue by KRGAMING2005** [PlaceholderAPI/PlaceholderAPI#227]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

When i type /papi reload it sends a message in red "An error occured while attemptiong to perform this command"

### Expected behaviour
> What should PlaceholderAPI do?

It should reload so i can use the placeholders that i eclouded

### Actual behaviour
> What does PlaceholderAPI actually do?

It does not reload so i can use my placeholders but instead it just sends the red message

### How to reproduce
> What steps did you made, to get this bug?

1. I typed "/papi ecloud download LuckPerms"
2. I typed "/papi reload"

**Comment by Andre601** [comment]
[default-assignment]: https://github.com/lucko/LuckPerms/wiki/Extensions#extension-default-assignments
[legacy-extension]: https://github.com/lucko/LuckPerms/wiki/Extensions#extension-legacy-api
[update]: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5
[default-groups]: https://github.com/lucko/LuckPerms/wiki/Default-Groups

First of all: Please **always** check the console for errors.
Since you downloaded the LuckPerms expansion, is here the common v5 issues.

# Common v5 issues

## Plugin x spams errors about LuckPerms
If the error contains `Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms` then the plugin uses the old v4 API of LuckPerms, while you're using LuckPerms v5.
A solution to this problem is to [download and install the legacy-API extension][legacy-extension] into the `extension` folder located inside the `LuckPerms` folder. If no such folder exist, create it.
Also, please contact the developer of the plugin and ask them to update to the latest release of the LuckPerms API.

If the error however contains `Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms` then it is the exact opposite and you're using LuckPerms v4 while the plugin is using LuckPerms v5.
In that case, do you need to update LuckPerms to v5. A page explaining how to migrate from v4 to v5 can be found [here][update].

## The expansion for PlaceholderAPI/MVdWPlaceholderAPI doesn't work
Please refer to the above section for how to solve this.
Just note that the latest version of the expansion is only compatible with LuckPerms v5.

## Default assignments don't work
The default assignments got removed in LuckPerms v5.
A temporary solution is to [download and install the default-assignment exptension][default-assignment] into the `extension` folder located inside the `LuckPerms` folder. If this folder doesn't exist, create it.

This, however, should be treated as a temporary solution and you should switch to an [alternative method][default-groups] instead.

**Comment by Funny-cube** [comment]
On top of what @Andre601 said just update LuckPerms to v5 or higher to fix this issue.
