### ISSUE TITLE
RogueParkour-temporary

### ISSUE THREAD

**Issue by matahombres** [PlaceholderAPI/PlaceholderAPI#228]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [X] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [ ] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

Type: Expansion

Dependency: RogueParkour

File: Into eCloud

**Explanation for what:**
The plugin have the state "I AM CURRENTLY REWRITING THIS PLUGIN EXPECT AN UPDATE SOON", and the LeaderHeads not working... I made a placeholder for one server and I think it's good to share it

Placeholders and explanation:
**`%RogueParkour-provisional_top_<number>;<type>%`**
Get top score and have 2 types score or name
Type for default have score and this is one opcional argument
Support offlinePlayers

**`%RogueParkour-provisional_get_<player>%`**
Get score for one player.
Not support offlinePlayers (RogueParkour limit)

**Comment by aBooDyy** [comment]
Hello,
Added in [Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#rogueparkour) and [Plugins using PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#r) pages.
I believe that you meant `%RogueParkour-temporary_` instead of `%RogueParkour-provisional_` in the placeholders.

Unfortunately, the expansion hasn't got verified due to the way it works and the lag it would cause. However, users are still able to download it manually from the [eCloud](https://api.extendedclip.com/all/) and use it on their own.
We would be glad to verify it if it received some improvements.

Thanks for your contribution.

**Comment by matahombres** [comment]
I am update and fix minor errors (One for database connection). But i don't know if pass the verified. Could it be verified again?
