### ISSUE TITLE
1.8.8 MySQL not working

### ISSUE THREAD

**Issue by Vasily31** [PlaceholderAPI/PlaceholderAPI#273]
i have PlaceholderAPI 2.10.5, my server version is 1.8.8

credit loaded but not appearing in the game.

https://prnt.sc/ropsis
https://prnt.sc/ropst2
https://prnt.sc/ropsze
https://prnt.sc/ropte5

thank you

**Comment by Andre601** [comment]
Please one of the templates

**Comment by aBooDyy** [comment]
Hello @Vasily31,

The MySQL expansion isn't managed by clip, so you'll have to report this issue to the author of the expansion.

Here's some solutions you might want to try before reporting:
- Make sure you've downloaded the expansion and reloaded PlaceholderAPI after.
```
/papi ecloud download mysql
/papi reload
```
- Make sure that the expansion has been loaded by checking the console after reloading PlaceholderAPI or see if its listed in the loaded expansions list `/papi list`.
- Make sure you have the latest version of the expansion (`/papi info mysql`). If you don't, then redownload the expansion to get the latest version.

Issue closed because it's not related to us.
