### ISSUE TITLE
Request change placeholders - OreAnnouncer

### ISSUE THREAD

**Issue by AlessioDP** [PlaceholderAPI/PlaceholderAPI#285]
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

## Please read
This template is only for requesting new information to be added to the wiki or for updating of already existing information!  
Please use the [Request change (PlaceholderAPI)] template to ask for additions/changes to the plugin PlaceholderAPI.  
For reporting bugs of PlaceholderAPI use the [Bug report] template.

Also make sure that the [wiki] doesn't already have the change and that there isn't a issue about this change on the [issues] page.

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] New plugin/expansion supporting PlaceholderAPI.  
A new plugin/expansion uses and/or provides placeholders.
- [x] Placeholder(s) changed.  
An already listed expansion/plugin has new placeholders or old ones have changed.
- [ ] Plugin/Expansion no longer supports PlaceholderAPI and/or was deleted.
- [ ] Other: __________ 

### Info
> Please provide any information that is useful including links and images.  
> For plugins/expansion providing new placeholders or updating old ones, provide the placeholders (that have changed)

The full placeholders list is:
```%oreannouncer_player_destroy%
%oreannouncer_player_destroy_<Material>%
%oreannouncer_player_found%
%oreannouncer_player_found_<Material>%
%oreannouncer_player_foundin_<TimeRangeInSeconds>%
%oreannouncer_player_foundin_<TimeRangeInSeconds>_<Material>%
```

**Comment by aBooDyy** [comment]
Hello there,

Thanks for your time writing to us.
As we're slowly updating the wiki to just give a link to the plugin's wiki if it has one, I've updated your plugin section to give a link to your wiki so you don't have to inform us every time it gets updated.

Have a nice day,
aBooDyy

**Comment by Andre601** [comment]
This is kinda sad to read imo....
For me was the wiki always the main place to find the placeholders and now going to just link to the other wiki instead is a bit sad....

I think having a system where people could PR the changes themself would be a good alternative than "slowly updating the wiki to just give a link to the plugin's wiki if it has one" as you said yourself aBooDyy

**Comment by aBooDyy** [comment]
This has been requested/suggested by Clip (#212). 
It's much easier for the plugin's developers to update their wiki without having to open an issue/pull request to get the placeholders updated here too.
Requiring the user to open another link for some plugins wouldn't harm and it's better than delaying the update.

I have undiscussed plans for this wiki. We'll see what we can do about that, everything will be taken into consideration.
The process of updating the wiki is slow due to the lack of time, but anyway, delaying this is not an issue, the placeholders are still getting updated and everything.

Thanks for your suggestions and sharing your thoughts,
aBooDyy

**Comment by Andre601** [comment]
Still not really a nice thing.
If I want to find the placeholders for plugin X and go here, only to then get forwarded to the wiki of said plugin is this plain annoying.
The option to have changes being PR-able would imo already speed up stuff as you yourself wouldn't need to write/copy-paste the placeholders down, but instead only need to merge said PR.

There are even things like GitHub Actions, which would allow updating wiki-pages through PRs on a different repository.
Example: https://github.com/Andre601/OneVersionRemake/blob/master/.github/workflows/wiki.yml#L14-L23

I'm straight honest here: I feel really sad that a wiki that I myself spend a lot of time on starts to become like this, where it seems that you don't want to keep a central place for such info...
I myself would offer to help to update and maintaining the wiki if that really was a problem you guys face because of lack of time.

**Comment by aBooDyy** [comment]
I fully understand. Thank you for the huge contribution to the wiki, we appreciate that.
As I mentioned, everything will be taken into consideration.
