### ISSUE TITLE
Material section %player_name%

### ISSUE THREAD

**Issue by WeelHull** [PlaceholderAPI/PlaceholderAPI#286]
I wanted to know the most up to date of what should I introduce on the material: section to have a visible player head?

I've tried head;%player_name%
So

material: head;%player_name%

and it's not working just wondering what am I doing wrong as the console doesn't appear to be having any errors nor warning.

Many thanks in advance

**Comment by WeelHull** [comment]
I've closed it because I thought I was in the wrong place but apparently this is connected to deluxmenus?

**Comment by Andre601** [comment]
This is indeed the wrong place, as it is about PlaceholderAPI and not DeluxeMenus.

Please join the HelpChat discord to receive support with DeluxeMenus: https://helpch.at/discord

**Comment by aBooDyy** [comment]
Hello there,

You're actually in the wrong place. This repository is for [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) plugin only.
As @Andre601 mentioned, you should be asking in [HelpChat discord](https://helpch.at/discord) where you can ask about [DeluxeMenus](https://www.spigotmc.org/resources/deluxemenus.11734/) plugin.

Anyways, I'll give you the solution to this issue here, but ask in the correct place next time, please.
1. Make sure you have downloaded the Player expansion, by running the following commands:
`/papi ecloud download Player`
`/papi reload`
2. Switch the semicolon (`;`) to a dash (`-`). This has been changed in the latest updates of DeluxeMenus.

If this didn't work for you, ask in [HelpChat Discord](https://helpch.at/discord), please.

Have a nice day,
aBooDyy
