### ISSUE TITLE
Animations expansion update 1.0.5

### ISSUE THREAD

**Issue by Niall7459** [PlaceholderAPI/PlaceholderAPI#324]
11/06/2020
Change request on description for animations expansion as per release 5
- [x]  Placeholders changed

Hyperlink to wiki: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#animations

Updated raw markdown description, please ensure the links and formatting is kept:
START
/papi ecloud download Animations

Placeholder format:
```html
%animations_<tag>Text</tag>%
```

With implicit boolean flag set to true
```html
%animations_<tag option>Text</tag>%
```
With explicit options set
```html
%animations_<tag option=10>Text</tag>%
```
With bracket placeholders:
```html
%animations_<tag>{placeholder}</tag>%
```

Please note: When using placeholders within the animation text, you must use the bracket variant.
Use `{player_name}` instead of `%player_name%` within the <tag> </tag> tags.

A list of available tags and corresponding options can be found on [Animations and Modifiers](https://github.com/Niall7459/KiteBoard-Documentation/wiki/Animations-and-Modifiers)
END

**Comment by Andre601** [comment]
You should follow the provided issue templates.

Also, does the info you provide here not really make much sense, especially when it should be updated on the wiki since it follows specific styling guides.
I suggest displaying this information:

```
%animations_<tag>Text</tag>%
```

For placeholders, use `{}` instead of `%%` (`%animations_<rainbow>Welcome {player_name}</rainbow>%`

Current list of valid types:
- blink
- fadein
- fadeout
- glow
- left
- pause
- pulse
- rainbow
- wave
- right
- scroll
- typewriter
- healthbar

The options are set using XML-styled tags which allow additional options.  
Refer to the [dedicated wiki page](https://github.com/Niall7459/KiteBoard-Documentation/wiki/Animations-and-Modifiers#available-animations) for more information.

**Comment by Niall7459** [comment]
The format on types has been updated 

- Left Align: `<align left width=32>Text</align>`
- Right Align: `<align right width=32>Text</align>`
- Appear: `<appear>Text</appear>`
- Faded Appear: `<appear fade>Text</appear>`
- Erase: `<erase>Text</erase>`
- Faded Erase: `<erase fade>Text</erase>`
- Fading In: `<fade in>Text</fade>`
- Fading Out: `<fade out>Text</fade>`
- Format/Round `<format format=#.## mode=HALF_EVEN>Number</format>`
- Healthbar: `<healthbar symbol=♥ fill=&c empty=&7 size=10 max=20>{player_health}</healthbar>`
- Marquee/Scroll: `<marquee width=32 space=32>Scrolling text</marquee>`
- Pause: `<pause times=10>This text is repeated for 10 frames</pause>`
- Pulse: `<pulse color=multi pause=1>Pulsating text</pulse>`
- Rainbow:`<rainbow>Rainbow text</rainbow>`
- Shine/Glow: `<shine start=&9 middle=&4 end=&9 normal=&7>Shining Text</shine>`
- Typewriter: `<typewriter cursor=_ pause=10 reverse>Typing text</typewriter>`
- Wave: `<wave colors=&c,&e,&6,&a,&9,&1,&d>Wave text</wave>`

**Comment by aBooDyy** [comment]
[Updated](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#animations). Made some changes to what you've sent, hope they're good.
Thanks for letting us know!

Kind regards,
aBooDyy
