### ISSUE TITLE
BungeeCord support

### ISSUE THREAD

**Issue by Leonardo-DGS** [PlaceholderAPI/PlaceholderAPI#36]
It would be nice if you add support for BungeeCord, even if the placeholders in the BungeeCord plugins are not widely used

**Comment by darbyjack** [comment]
I don't really see a point for this. The reason being is that some expansions will throw errors due for the way the authors designed it because if it can't find their plugins, they will throw errors on loading. That's why it's a better idea to handle it per server vs having it globally.

**Comment by Leomixer17** [comment]
@darbyjack I'm saying to add support to set placeholders in the BungeeCord, to use placeholders with BungeeCord plugins

**Comment by darbyjack** [comment]
That is up to the authors of the plugins themselves to add PlaceholderAPI support.

**Comment by Leomixer17** [comment]
@darbyjack But PlaceholderAPI doesn't support BungeeCord plugins, I'm asking to add support to it

**Comment by darbyjack** [comment]
Of course it supports BungeeCord plugins, they just have to make their own support.

**Comment by extendedclip** [comment]
Some plugins such as BungeeTabListPlus already support PlaceholderAPI at the proxy level:
https://github.com/CodeCrafter47/BungeeTabListPlus/blob/master/bukkit/src/main/java/codecrafter47/bungeetablistplus/bukkitbridge/placeholderapi/PlaceholderAPIHook.java

**Comment by extendedclip** [comment]
Ah I get you.

Would the placeholder system be specifically used with Bungee plugins or would there need to be communication between the proxy and server?  

Ex: ability to register "Bungee placeholders" in the "Bungee PAPI" then these placeholders are accessed from the Spigot server

**Comment by Leomixer17** [comment]
@extendedclip The placeholder system will be specifically used with Bungee plugins

**Comment by Bernard2518141184** [comment]
I believe a lot of people wanted the official bungeecord dedicated placeholderapi. Simply change all org.bukkit.entity.Player to net.md_5.bungee.api.connection.ProxiedPlayer, sending messages, etc. to make it compatible with bungeecord. The structure of the placeholderapi remains the same. However, since this is dedicated for bungeecord, another ecloud may be required. Bukkit (spigot) placeholders cannot be downloaded to bungeecord papi, while bungeecord placeholders cannot be downloaded to spigot papi.

I hope this helps.

**Comment by NEZNAMY** [comment]
Good idea, hooking into both bungee plugins and bukkit plugins via bridge plugin would be really great !
