### ISSUE TITLE
[PlaceholderAPI/PlaceholderAPI] Run failed: Update Wiki - master

### ISSUE THREAD

**Issue by extendedclip** [PlaceholderAPI/PlaceholderAPI#387]
## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

Seems that the github actions don't work correctly. I just got this email on merge

![issue](https://img.extendedclip.com/chrome_2020-07-28_11-15-51.png)

### Expected behaviour
> What should PlaceholderAPI do?

not fail on merge

### Actual behaviour
> What does PlaceholderAPI actually do?

fails on merge

### How to reproduce
> What steps did you made, to get this bug?

1. push something

### Installed expansions
> Please list all expansions that are displayed when running `/papi list`

[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

**Comment by Andre601** [comment]
> could not read Password for 'https://***@github.com': No such device or address

This confirms my belief that this action requires a PAT (Private Access Token) in order to function.
Someone that has both push access and access to the repo's settings has to create a PAT with `repo` scope (https://github.com/settings/tokens/new?scopes=repo) and add a new secret (Settings -> Secrets -> Add new) to the repo that contains the generated PAT as value.

You can then give me the name of the secret (Call it something like PAT) or update the workflow yourself by changing `${{ secrets.GITHUB_TOKEN }}` with `${{ secrets.SECRET_NAME }}` (SECRET_NAME is obviously the name you gave the secret)

There isn't anything I can do here as it is an issue with GitHub's OAuth flow or whatever...

**Comment by extendedclip** [comment]
Will this information be kept private though? I wouldn't want a PAT sitting here in a public repo for whatever we choose to do with it.

**Comment by Andre601** [comment]
Secrets are only displayed as *** in the workflow and once you've set it can nobody open/edit it again. Only delete it.

**Comment by Andre601** [comment]
Is now fixed using a PAT.
But I will try to look for an alternative that just uses the github token that is provided for actions instead of a PAT.
