### ISSUE TITLE
[Discussion] Do not use OfflinePlayer and enforce non-null online players

### ISSUE THREAD

**Issue by MrIvanPlays** [PlaceholderAPI/PlaceholderAPI#419]
### Type
- [x] Change to code (External).  

### Description
Whoever made this is someone who doesn't understand api design
![image](https://img.mrivanplays.com/rh8VNTW0DT.png) 

My request is simple: enforce online players. 
Why? First, backwards compatibility. API design is the politics game and you can't go breaking it without solid argument. I don't see ANY solid argument for breaking the working PlaceholderAPI#setPlaceholders(Player, String) . 
Second, the majority of expansions and plugins who add placeholders require online player to function properly and changing that would break MASSIVE amount of plugins adding their placeholders which would result in children reviewing 1 star completely working plugins. Yes java will fallback to the offline player method for plugins only applying placeholders, that's not the problem here. The problem is the expansion support and plugins adding placeholderapi right now which compile against 2.10.8, which requires a ugly cast to make ide not scream at you. 

And now, a message to the one who made the change I have showed at the start (_credits to aikar and starlis/empirecraft for writing that short explanation_):
API's are tough to design. In public projects such as Bukkit, Spigot, Sponge etc, once an API is commited. **It's almost forever. You can't go breaking it without solid justification. This is the politics game.**

**Comment by Andre601** [comment]
PlaceholderAPI did use OfflinePlayer since quite some time now and even recommended it over the Player option for multiple reasons:

1. OfflinePlayer is nullable while Player would cause exceptions to happen.
2. Not every expansion requires a Player instance to be used so it is often simpler to have null being passed in those situations instead of first trying to get a Player instance somewhere to then use for nothing.
3. You can easly use a Player instance for the OfflinePlayer parameter without any major complications or disadvantages.

> Why? First, backwards compatibility. API design is the politics game and you can't go breaking it without solid argument. I don't see ANY solid argument for breaking the working PlaceholderAPI#setPlaceholders(Player, String) .

I just explained it in point 3. You can just pass a Player instance to the OfflinePlayer argument (Maybe with or without casting) and it will work just fine, so this argument is redundant.
A simple casting such as `Player p = (Player)offlinePlayer;` is really not that bad, or otherwise all the `Player p = (Player)server` castings made in plugins would be ugly too in your opinion.

> API's are tough to design. In public projects such as Bukkit, Spigot, Sponge etc, once an API is commited. It's almost forever. You can't go breaking it without solid justification. This is the politics game.

I say no here. You CAN break an API. Deprecation exists for a reason and your image shows clearly that the methods do exist, but are marked as deprecated, meaning that they will be removed in a future release and should therefore not be used.

Here is a description of the `@Deprecated` annotation from the [Java 8 Javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/Deprecated.html)
> *A program element annotated [at]Deprecated **is one that programmers are discouraged from using, typically because it is dangerous, or because a better alternative exists.** Compilers warn when a deprecated program element is used or overridden in non-deprecated code.*

The argument you provided here from Aikar and friends is essentially bullshit. An API is not set in stone. It evolves and methods change and get replaced over time.

It may be common practice for Bukkit, Spigot and Paper to deprecate stuff and never remove it because it's "almost forever" but this way of thinking shouldn't be applied to all APIs out there.
APIs like JDA do deprecate and remove methods in later releases as that's how it should go. Keeping deprecated methods over decades is no solution you should approach at all. Your API should be a clean and easy to understand thing and not a collection of outdated methods.

If you want to give reasons for why not do what we do, then don't use horrible examples/role models just as Bukkit, Spigot and PaperMC (Yes, I know PaperMC improves Spigot, but patching shit code still gives back shit code) because looking at the general code and how much people like MD_5 care for proper documentation (Like only have `@deprecated` without any reason or replacement mentioned) would I really search for another (maybe not MC related) API that does what they believe is the best practice here.

**Comment by MrIvanPlays** [comment]
You're breaking completely working functionallity which isn't unsafe. This is just going to lead to more developers making their own alternatives of placeholderapi or use already existing ones (like mvdw's, although maxim doesn't suggest using it in his plugins except if we're adding placeholders) because no one knows shit about what api are you going to break every now and then. 

Yes when you put a `@Deprecated` annotation you have to remove the method at some point (that's one of the reasons why bukkit api sucks, not removing the classes/methods after putting it), but you're putting it like it doesn't matter we will break some plugins. Remember: placeholderapi is used by 80% of the developers making bukkit plugins (maybe more), and every api break can break thousands of plugins and that's why you don't break api without a solid argument. Yes you CAN break it, but before breaking it think about the consequences that will happen after breaking it.

> You can easly use a Player instance for the OfflinePlayer parameter without any major complications or disadvantages.

Yes I know that OfflinePlayer is a superclass of Player as I mentioned in my initial statement, however at current placeholderapi version you can't because of PlaceholderAPI#setPlaceholders(**Player**, String) and because you put a `@ScheduledForRemoval`  annotation ide screams at you for using that method and that's why you have to do a cast which would be unnecessary if you didn't break this completely working api (again, I don't see ANY solid reason for removing that method except "we have that, you use that or go fuck yourself"). 
I will repeat it again, I don't see ANY solid reason for removing that.

> Not every expansion requires a Player instance to be used so it is often simpler to have null being passed in those situations instead of first trying to get a Player instance somewhere to then use for nothing.

Just because 1% of the expansions don't use the Player class doesn't mean we should replace it with a nullable OfflinePlayer. Developers are already used to applying placeholders with a player instance as most of the cases whereever you use placeholderapi you already have a player instance (say sending a message and applying placeholders to that message) 

> There is in fact even a `getPlayer()` method for OfflinePlayer to get a Player instance (if available) that exists since at least Spigot 1.8(!) so your "I have to make a ugly casting" is also redundant here.

I explained earlier why it isn't redundant. Also proof:
![image](https://img.mrivanplays.com/idea64_E12cfjEsA0.png) 
Also I know about the existence of `getPlayer()` and most of my plugins don't support 1.8 so idrc about that lower of a version support.

> Your API should be a clean and easy to understand thing and not a collection of outdated methods.

And that's where rewrites come in. When you don't like something, you rewrite it, and make a major version out of it.

**Comment by Andre601** [comment]
You should've mentioned it more clearly that you're talking about the `setPlaceholder` method here. I can see now where this would be an issue and will propose that this change will be reverted.

**Comment by MrIvanPlays** [comment]
> You should've mentioned it more clearly that you're talking about the `setPlaceholder` method here. I can see now where this would be an issue and will propose that this change will be reverted.

Not only, nullable OfflinePlayers is also a problem. NPEs will come from everywhere when it gets enforced.

**Comment by extendedclip** [comment]
We are going to remove the deprecation from the 2 setPlaceholders methods that accept player and allow both although the onRequest method in expansions will stay the same until 3.0.

**Comment by MrIvanPlays** [comment]
> onRequest method in expansions will stay the same until 3.0.

I don't have a problem with that, as I said earlier there's also a problem with the nullable OfflinePlayers so enforce a non null players in all setPlaceholder methods that are going to stay.
