### ISSUE TITLE
Can you find number of players in a group of worlds?

### ISSUE THREAD

**Issue by CrazyMMG** [PlaceholderAPI/PlaceholderAPI#428]
Just wondering if there was a way to find the number of players in a group of worlds? I can find the number of players in one world but in need to find the number in a group. Sorry for not using the format, im in a rush. 

Thanks,
CrazyMMG

**Comment by Andre601** [comment]
Even if you're in a rush is that no reason to ignore the templates. They exist for reasons.

It's also better to ask in the [Discord Server](https://discord.gg/helpchat) since you can get much faster support there for questions.
I suggest you go to the [World-Expansion Repository](https://github.com/thienbao860/World-Expansion/) and suggest to add this feature there.

**Comment by cj89898** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#PlayerList
