### ISSUE TITLE
PlaceholderAPI.registerExpansion() method not available despite scheduled removal later

### ISSUE THREAD

**Issue by JCulley** [PlaceholderAPI/PlaceholderAPI#445]
### Issue
There seems to be a disconnect in the API deprecation vs what is actually available right now. In the code it has an annotation for `@ApiStatus.ScheduledForRemoval(inVersion = "2.11.0")` https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/PlaceholderAPI.java#L272 however it appears to have already been removed in the latest version 2.10.9 available on Spigot MC now.

### Expected behaviour
The method should still be available.

### Actual behaviour
The method is not available.

### How to reproduce
Attempt to access the static method in the PlaceholderAPI class.

**Comment by Andre601** [comment]
This is not a bug and also not the case.

The GitHub code is (at least) always the same as the latest spigot release (you can check the code at the time of the 2.10.9 release).

The ScheduledForRemoval annotation will also cause the IDE to display an error, so this could also be caused by it.

Anyway, this isn't a bug as you're not supposed to use those methods anyway.
If you have plugins using those methods, update them or nag the author about it.

**Comment by JCulley** [comment]
@Andre601 thanks for taking the time out of your day for your response.

1) Don’t understand how something being removed abrupt and prematurely is “not the case”. The method is not in the latest version, what’s up for debate here?

2) Well I guess this is one of those “maybe” cases as I’ve pointed out.

3) The method does not exist at all in the version, blaming the annotation has absolutely nothing to do with it.

4) Saying it isn’t a bug because we’re “not supposed to use those methods” is the worst response I’ve heard in a while. I have indeed updated my plugins seems how this abrupt change was made without any communications and still with the belief it was slated for removal later. I was simply brining the issue to light but if you want to respond as you have then why bother putting any scheduled removal annotations whatsoever seems how they don’t mean anything apparently.

Cheers mate.

**Comment by Andre601** [comment]
> 1. Don’t understand how something being removed abrupt and prematurely is “not the case”. The method is not in the latest version, what’s up for debate here?

The debate here is whether it's worth it or not to update the downloads just to add a method that was planned for removal anyway.
The `PlaceholderExpansion#register()` existed for quite some time now, the wiki mentioned it in its examples too, so the question if we should update the releases (or even make a new one) just to re-add this isn't really an important one.

> 3. The method does not exist at all in the version, blaming the annotation has absolutely nothing to do with it.

Looking at the code, are you right about this. Clip added this after the 2.10.9 release (I was unable to check the code at the time of release because I was using GitHub for Android which doesn't have this feature yet).
But again: I see no real reason to update or make a new release just to add two methods back that are deprecated and where not recommended for use for quite some time now.

I'll leave this up to @extendedclip whether he wants to do such an update or not, but I personally vote against it.

> 4. Saying it isn’t a bug because we’re “not supposed to use those methods” is the worst response I’ve heard in a while. I have indeed updated my plugins seems how this abrupt change was made without any communications and still with the belief it was slated for removal later. I was simply brining the issue to light but if you want to respond as you have then why bother putting any scheduled removal annotations whatsoever seems how they don’t mean anything apparently.

I still don't see it as a bug. You can see it as a human error of kinds but it isn't really a bug. For me is a bug, when a piece of code doesn't work as expected or causes unwanted side-effects.
Here the code in question doesn't even exist in the first place. Of course everyone has their own interpretation about what a bug is, so this is mine.

Also, for the record [2.10.7]() was the version that removed methods like PlaceholderAPI.registerExpansion and Versions 2.10.8 and 2.10.9 tried to revert those changes as they where way too large to justify just a small version change (should've been 2.11.0 or contain the methods as deprecated, yet still supported).
The question here is - again - whether making a release just to re-add 2 methods that are not supposed to be used, are only used by few plugins (And those that use it are most likely outdated and/or not supported anyway) and that aren't even explained nor recommended in the documentation would make any sense.
It would be just an update with no real benefit for the larger audience.

But again: I leave this up for clip to decide.

**Comment by extendedclip** [comment]
Blame me. I missed adding this method back when I added everything else back but I ended up adding it after release of 2.10.9. Either way should just use Expansion methods to register rather than registering through the PlaceholderAPI class.
