### ISSUE TITLE
Expansion-listplayers.jar seems to be outdated

### ISSUE THREAD

**Issue by Zefferis** [PlaceholderAPI/PlaceholderAPI#456]
### Issue
I was previously using PAPI 2.10.6 and the expansion listplayers.jar was working as a means to tell my players who was in which world, I recently updated to 2.10.9 & 2.10.10-Dev108 and this expansion no longer works in both versions, when registered it throws the following error:

```
[Fri, 28. Aug 2020 16:11:00 BST INFO] Zefferis issued server command: /papi register Expansion-listplayers.jar
[Fri, 28. Aug 2020 16:11:00 BST WARN] listplayers is attempting to register placeholders via a PlaceholderHook class which is no longer supported!
```

### Expected behaviour

Not throw said error for said expansion; list players with the placeholder

### Actual behaviour

Throws the expansion back with no interaction

### How to reproduce

1. Have Papi Installed with the listplayers expansion, attempt to register/parse the placeholder

### `/papi dump` output

https://paste.helpch.at/uhenuwoloh

**Comment by Andre601** [comment]
This isn't a bug. It's an intentional behaviour. The warning clearly tells you what is happening: The Listplayers expansion is trying to register through PlaceholderHook which isn't recommended nor supported since ages.

You perhaps can use the [Worlds Expansion](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#world) to tell who was in which world (i.e. `%world_recentquit_<world>%` for who recently left in world `<world>`)

But again, this is not a bug.
