### ISSUE TITLE
Time played statistic placeholder thinks there are 60 hours in a day

### ISSUE THREAD

**Issue by JHarris12345** [PlaceholderAPI/PlaceholderAPI#476]
### Issue
The placeholder {placeholderapi_statistic_time_played} in 1.16 believes there is 60 hours in a day. You can see from the screenshot below it says 22 days and 36 hours. This has caused everyones playtime to durastically decrease. Mine was at 92 days but now thinks I have 22 days due to there being 40 hours more in a day.

![image](https://user-images.githubusercontent.com/46936647/93087457-7cef4300-f690-11ea-9755-76595f898459.png)

### Expected behaviour
There should be 24 hours in a day

### Actual behaviour
It goes up to 60

### How to reproduce
Use the {placeholderapi_statistic_time_played} placeholder and play for over 24 hours

1. 

### `/papi dump` output
https://paste.helpch.at/omitogiqej

**Comment by Andre601** [comment]
This is an issue caused by the Statistic-expansion and not PlaceholderAPI.

A quick research showed me this:
- [Line 103 of StatisticsExpansion is called for time_played](https://github.com/PlaceholderAPI/Statistics-Expansion/blob/master/src/main/java/com/extendedclip/papi/expansion/mcstatistics/StatisticsExpansion.java#L102-L104)
- [Line 123 of the StatisticsUtil handles this](https://github.com/PlaceholderAPI/Statistics-Expansion/blob/master/src/main/java/com/extendedclip/papi/expansion/mcstatistics/StatisticsUtils.java#L123)
- No PlaceholderAPI method is used to format the time.
- This issue is [already known](https://github.com/PlaceholderAPI/Statistics-Expansion/issues/20)
