### ISSUE TITLE
Intense lag from Players connecting (setting placeholders events)

### ISSUE THREAD

**Issue by Esronn** [PlaceholderAPI/PlaceholderAPI#531]
### Issue
When we get a few players the TPS suddenly drops a lot (down to 4-5), the only thing that Spark and Timings show as a issue every time is an event from Papi.
I tried it on an empty (no other plugins) server as well as on our production server, same issue.

Things from the production server using Tuinity:
Timings: https://timings.aikar.co/?id=3e93d8bc7fd74410814e6c7af567911f
Sparks profiler: https://spark.lucko.me/#70nD7o7tdl
PAPI Dump: https://paste.helpch.at/jadatagire

### Expected behaviour

Not lag.

### Actual behaviour

It seems like this:
me.clip.placeholderapi.PlaceholderAPI.setPlaceholders()
Takes A LOT of time.

### How to reproduce

I don't really know.
1. Install latest Paper or Spigot.
2. Install clean version of latest Papi.
3. Have at least 15-20 players join the server.
4. Watch TPS.

### `/papi dump` output

https://paste.helpch.at/jadatagire (same link as above)

**Comment by Andre601** [comment]
There are some inconsistencies that make me struggle to understand things.
In your "How to reproduce" do you say we should use Spigot or paper and have at least 15-20 players joining, while in your issue description, you mention that you're using Tuinity and also tried it on an empty Server?

I also honestly don't believe that on your Test Server, PAPI was the only plugin installed as otherwise the setPlaceholders method, which according to your spark report could be the root of the issue, would've never been triggered at all as no plugin/expansion would be active to render placeholders.

Please give us a clear and 100% reproducable setup so that we can really check it.
My personal guess is, that the real cause is more the TAB plugin you use or the fact that you're using Tuinity.

Please try it out with a basic Paper Server setup and only PAPI installed and afterwards add the TAB plugin to test.
If the lag doesn't happen at all: Blame Tuinity for doing something wrong.
If the lag appears AFTER TAB was installed: Blame that plugin.
If the lag appears regardless of the setup, let us know with a detail report.

**Comment by Andre601** [comment]
Also, to add to this; Further looking into this shows, that the last PAPI related log in the Spark Report is the `onRequest()` of the Server-Expansion.
So this might actually be caused by the server expansion itself and not PAPI, so please also check, if the lag is gone when the Server-Expansion is uninstalled.

**Comment by darbyjack** [comment]
Any chance you're using the `%server_total_chunk%` placeholder? It looks like it might be coming from that.
