### ISSUE TITLE
Optional colorize boolean (PlaceholderAPI#setPlaceholders)

### ISSUE THREAD

**Issue by yakovliam** [PlaceholderAPI/PlaceholderAPI#537]
### Type

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description

Add a boolean `colorize` to `me.clip.placeholderapi.replacer.Replacer.java` (default=true) to give developers the option of colorizing or not. This would be implemented in a new method `#setPlaceholders(..., boolean colorize)`.
Reasoning - sometimes the developer does not want compulsory coloring of their input text.

**Comment by Andre601** [comment]
[This was a thing before](https://github.com/PlaceholderAPI/PlaceholderAPI/pull/234).

It was later changed since the API became a huge mess with a lot of pointless methods to use and we wanted to clean it up a bit. Even now without this option does PAPI have 10 different options (4 `setPlaceholders`, 4 `setBracketPlaceholders` and 2 `setRelationalPlaceholders`) and adding this option would at least double the amount.

In addition am I not even 100% sure if it would be that easy to change the way PAPI is currently handling the Strings. It could be a simple line change but also a major rewrite of the Parsing function.

I vote against this, as for the aforementioned reasons.
