### ISSUE TITLE
[BUG] %player_last_damage% not working

### ISSUE THREAD

**Issue by TNG-China** [PlaceholderAPI/PlaceholderAPI#56]
Placeholder **%player_last_damage%** always return **0.0**, No matter how damage you dealt.

**Comment by TNG-China** [comment]
Expansion Test:
![image](https://user-images.githubusercontent.com/21065884/48969073-2be20b00-f034-11e8-8200-6449c487615b.png)

monster health:
![image](https://user-images.githubusercontent.com/21065884/48969092-546a0500-f034-11e8-963a-730251ed6f97.png)

**Comment by iGabyTM** [comment]
@TNG-China, the placeholder `%player_last_damage%` show the last amount of damage taken.
![Image](https://i.imgur.com/085gxJX.png)
```java
            case "last_damage":
                return String.valueOf(p.getLastDamage(
```

**Comment by TNG-China** [comment]
@iGabyTM Oh, I see, It's the amount of damage taken, not dealt. But i need dealt amount , Any chance add?

**Comment by Andre601** [comment]
Sorry for the late response.

> @iGabyTM Oh, I see, It's the amount of damage taken, not dealt. But i need dealt amount , Any chance add?

This could be possible by checking if the player has done any damage towards an entity.
The question here tho is, if that is doable through an expansion, since as far as I know do we have to listen for an event (`PlayerDamageEntityEvent` if I remember correctly) which would require us to implement EventListener and such into the expansion.
And there is also no method provided by spigot, to get the last damage dealt towards a entity.

But at the end is this completely up to the dev(s) of the expansion, if they want to implement it or not.
I recommend asking in the [Player-expansion](https://github.com/PlaceholderAPI/player-expansion) repository, if this is possible to add.

**Comment by Andre601** [comment]
I moved this now feature request to the Player-expansion repository
https://github.com/PlaceholderAPI/Player-Expansion/issues/13
