### ISSUE TITLE
%pinger_isonline% problem

### ISSUE THREAD

**Issue by FuZyKingZ** [PlaceholderAPI/PlaceholderAPI#67]
Hello,

So my Hub is running (Spigot 1.12.R0.1-SNAPSHOT   PlaceholderAPI 2.9.2)
My Survival is running (Spigot 1.13.2-R0.1-SNAPSHOT   PlaceholderAPI 2.9.2)
My Creative is running (Spigot 1.12.2-R0.1-SNAPSHOT   PlaceholderAPI 2.9.2)

In the hub I am trying to use %pinger_isonline_REDACTED:35540% 
35540 is my survival server port the server is online and I can play it fine but when I try and use the placeholder it displays "Offline"
but then when I try to ping my 1.12.2 skyblock server it says "Online"

**Comment by Andre601** [comment]
Sorry for the late response.

Does this also happen with your creatîve server (when you use the port of it)?
If no, then my guess is, that the Pinger-placeholder doesn't work with 1.13.2 servers.
But I can't tell why that would be the case.

Also as a little note: I removed the images and changed the provided placeholders, due to showing the IP. (Redacted for security reasons)

**Comment by Andre601** [comment]
Closed due to no response from author within 3 days.
