### ISSUE TITLE
Removal or togglability of PAPI's debug messages in the console - doesn't check for invalid placeholders if turned off

### ISSUE THREAD

**Issue by TheJoshue** [PlaceholderAPI/PlaceholderAPI#697]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New config option

### Description

Removal or togglability of debug messages in the console, for example:
```
[Math] Cause: '24-NoData' is not a valid Math-Expression.
[11:34:34 WARN]: [PlaceholderAPI] [Math] Invalid Placeholder detected!
[11:34:34 WARN]: [PlaceholderAPI] [Math] Placeholder: %math_0:_{statistic_mine_block:STONE}-{custom_placeholder_that_when_temporarily_doesnt_have_data_output_so_it_displays_text}%
```

Thanks in advance i hope this will make sure that we go one step futher with the enhancements.

**Comment by Andre601** [comment]
This is from the math expansion and not PlaceholdrAPI.
PlaceholderAPIhas no say in this as the expansion is the one printing the message and it won't be changed. The warnings exist for valid reasons.

**Comment by TheJoshue** [comment]
i can send you example of my menu so you can see that in my menu the warning isn't needed

**Comment by Andre601** [comment]
Again, this is not a PlaceholderAPI issue and therefore doesn't belong here.
And the fact this warning shows up is a clear indicator that there is something wrong with your placeholder.

You return a invalid math expression and this is the result, so better fix this issue rather than asking us to hide clear warnings.

https://github.com/Andre601/Math-Expansion/blob/master/src/main/java/com/andre601/mathexpansion/MathExpansion.java#L118-L120
