### ISSUE TITLE
Oi! Add my Expansion to the wiki <3

### ISSUE THREAD

**Issue by Artitus** [PlaceholderAPI/PlaceholderAPI#75]
I wrote this expansion a while back and never had it added to the wiki page... so here I am.
https://api.extendedclip.com/expansions/disease/
https://github.com/Artitus/PAPI-Expansion-Disease

### Type
> What kind of change is it? (Multiple selections possible)

- [ ] Placeholder(s) changed.
- [x ] New placeholder(s).
- [ ] Plugin no longer supports PlaceholderAPI and/or was deleted.

### Plugin
> What is the name of the plugin?

Disease
https://www.spigotmc.org/resources/disease.3911/

### What is the new value?
> **Placeholder(s) changed**: Type what the old and the new placeholder(s) is/are.  
> **New Placeholder(s)**: Type the new placeholder(s).  
> **Plugin no longer supports PlaceholderAPI**: Leave this blank.

%disease_disease%
%disease_sickness%
%disease_temperature%

**Comment by Artitus** [comment]
Also just noticed my java class doesn't match the same method calls as the current example expansion class. Do I need to update my repo and expansion or should it still work?

**Comment by Andre601** [comment]
I added the placeholders.

And to answer your question(s).
It's generally recommended to use the latest functions of PlaceholderAPI since older ones can become deprecated or even get removed in newer versions.
Also in case of latest PlaceholderAPI (2.9.2) is it also possible to use `OfflinePlayer` which now doesn't require you to have an (online) player for the placeholders (That already was the case before but I hope you know what I mean.)

Also, I recommend to not call your main class `Main`, since this is kind of bad practice in terms of development.
