### ISSUE TITLE
MagmaMC placeholderapi got Stuck

### ISSUE THREAD

**Issue by pinchiguillo** [PlaceholderAPI/PlaceholderAPI#761]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin/Server Incompatability

### What happens?

I am setting up a server using macmamc (plugins and mods). When starting the server without any expansion of PlaceholderApi it starts correctly.
When I use the command
/ papi ecloud download and / papi reload the expansions load correctly, but when restarting the server it stops at

[Server thread / INFO] [me.clip.placeholderapi.PlaceholderAPIPlugin]: [PlaceholderAPI] Placeholder expansion registration initializing ...

without any error or something.

Installed extensions:
Player
Luckperms
(with the command papi ecloud download)

### Expected Behaviour

I was expecting a correct start of the server or at least an error to know where to start looking for that fails

### How to Reproduce

1. Use MacmaMC in 1.12.2
2. Install placeholderapi-2.10.9
3. /papi ecloud download LuckPerms
4. /papi ecloud download Player
5. /papi reload
6. Reboot server

### `/papi dump` Output

N/A

### Console Log

https://paste.helpch.at/utupulicig.md

**Comment by Andre601** [comment]
We do not really support Hybrid Servers since those kind of servers can and will break a lot of plugins.

Those kind of servers are bad as they try to combine two APIs which would never work together to begin with: On one side the fairly rigit Bukkit-API and on the other a somewhat lose and frequently changing Forge-API.

I highly recommend to not use those hybrids and instead use only one side.
I also recommend reading the [PSA of EssentialsX](https://essentialsx.net/do-not-use-mohist.html) about hybrid servers. While it mostly talks about Mohist does most of its parts fit towards any other Hybrid server.

Either way, this is something we can't and won't fix.
