### ISSUE TITLE
%server_time_HH:mm:ss% with DST support

### ISSUE THREAD

**Issue by Vizis** [PlaceholderAPI/PlaceholderAPI#78]
Is there way to include DST to %server_time_HH:mm:ss% ?
Scoreboard shows e.g.  21:00:00 but it's 22:00:00 cause of DST (day saving time)
Lastes papi on 1.12.2 spigot server.

**Comment by Andre601** [comment]
[SimpleDateFormat]: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

The placeholder uses the [SimpleDateFormat] which can include the time-zone, which can be shown through the letters `z`, `Z` or `X`.

There is to my knowledge no way to actually show the time with(out) an offset, so that is most likely the only way you could do it.

**Comment by Andre601** [comment]
[Server-Expansion]: https://github.com/PlaceholderAPI/Server-Expansion

One thing you could maybe do is go to the repository of the [Server-expansion] and ask there, if it would be possible, to add an option for a time-zone to be used. (Like a config option.
Another option would be to add a general/default option to PlaceholderAPI, to define the default time-zone.
