### ISSUE TITLE
Waterfall and/or Travertine Expansion

### ISSUE THREAD

**Issue by Neeonn** [PlaceholderAPI/PlaceholderAPI#81]
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Bug report]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
[wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### Notes
This template is for **requesting additions for the wiki** and not for reporting bugs or requesting changes for the wiki!  
If you want changes to be made to the wiki, use the [Request change] template.  
For bug reports, use the [Bug report] template.

Also make sure, that your requested placeholders/plugin isn't already added in the [wiki] or listed in the [issues] page.

### Type
> What kind of request is this? (Multiple selections possible)

- [x] New expansion providing placeholders.
- [ ] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

Waterfall and/or Travertine

### Placeholders/others
> What are the new placeholders/Any additional info?

%waterfall_total% %waterfall_servername% (Online count like for the Bungee expansion)

**Comment by Andre601** [comment]
I can't seem to find the expansion with either the name `Waterfall`, nor `Travertine`
Are you sure the expansion is on the ecloud AND verified?

**Comment by Neeonn** [comment]
The expansions don't exist, I'm requesting for them to be made.

**Comment by Andre601** [comment]
You should've read the description of the issue template.
This template is for requesting placeholders/plugins to be added to the wiki and not for asking for placeholders to be made.

Also as far as I'm aware can you simply use the BungeeCord placeholders because after all are Waterfall and Travertine forks of it, that add stuff like support for 1.7 clients and servers.

If it doesn't work, feel free to open a new issue. Just don't use a template then.

**Comment by Neeonn** [comment]
Oh sorry, I didn't read it.
