### ISSUE TITLE
Placeholders with Essentials

### ISSUE THREAD

**Issue by Smurfboi007** [PlaceholderAPI/PlaceholderAPI#841]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [x] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

Hi! I've talked to the guys at Essentials X, they walked me through a couple of solutions, and it didn't work. When I turned off placeholderAPI, it worked perfectly fine. This is the line that is causing it:

` format: '&6[&3LV. &l%superior_island_level%&6] &r{DISPLAYNAME}&8» &r{MESSAGE}'`

From essentials, if I remove `%superior_island_level%` It works, if I turn off placeholderAPI it works. I have superiorskyblocks2 placeholder extension installed. I use placeholder API for the scoreboard as well, there it works. But not in this config, here is my Essentials X issue, if you want to read through it: https://github.com/EssentialsX/Essentials/issues/4936.

https://essentialsx.net/dump.html?id=564254946a384985b23185612c5c591a

### Expected Behaviour

The message should display the placeholder.

### How to Reproduce

1. I have no idea, that's why I am asking

### `/papi dump` Output

https://paste.helpch.at/amuqinosum

### Console Log

https://paste.helpch.at/woxaquhobu.md

### Errors

https://paste.helpch.at/otilimidag.sql

**Comment by Andre601** [comment]
EssentialsXChat uses `setFormat` which sets the chat message.
This method requires two `%s` placeholders to be proved, so that the server can replace them with the player name snd message respectively.

Your setup messes this up. To my knowledge is EssentialsXChat not even supporting PlaceholderAPI placeholders yet, so your issue is that you are providing an invalid format.

It's not a PlaceholderAPI issue.
