### ISSUE TITLE
Add a command to see the placeholders of plugins that support PAPI plugins

### ISSUE THREAD

**Issue by TeQTabanca** [PlaceholderAPI/PlaceholderAPI#968]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

Minor Code improvement (Won't affect Servers)

### Description

**When I looked at the plugin's commands, I only saw the _/papi ecloud placeholders <expansion_name>_ command, but I couldn't see the _/papi placeholders <plugin_name>_ command.**

**The reason this feature was added is because the authors of some older plugins did not update the placeholders in the plugin's wiki, so I need this command...**

**Comment by Andre601** [comment]
The question is, how should we obtain the placeholders?

A placeholder can be virtually anything and the ecloud command only works because authors can set their placeholders there for PlaceholderAPI to download.

There is iirc a method to return a list of Placeholders inside the PlaceholderExpansion itself. The issue I see with this is, that barely anyone knows about this, so I doubt people would use it.

**Comment by TeQTabanca** [comment]
> The question is, how should we obtain the placeholders?
> 
> A placeholder can be virtually anything and the ecloud command only works because authors can set their placeholders there for PlaceholderAPI to download.
> 
> There is iirc a method to return a list of Placeholders inside the PlaceholderExpansion itself. The issue I see with this is, that barely anyone knows about this, so I doubt people would use it.

**I think this might be the most necessary command for the plugin. Because this plugin only runs placeholders set by other plugins. Placeholders need a name to run. We only need to look at the plugin's wiki to look up the name of the placeholders, but if we use the "/papi placeholders" command, we don't need the wiki. If the plugin has already been abandoned, wiki pages often do not work or contain outdated information.**

**Comment by Andre601** [comment]
Please read again what I've written as you clearly ignored the majority of my points.

We can add a command. That wouldn't be the problem.
The problem is where to get the necessary data from.

PlaceholderAPI doesn't have any kind of algorithm or similar that can recognize what kind of Placeholder Pattern an expansion has.
The fact that the `ecloud placeholders` command works is simply due to the fact that every expansion page has a Placeholders section, which PlaceholderAPI pulls data from.

Also, if we now would make a command which gets the placeholders from the expansion itself (Through the `getPlaceholders()` method mentioned in my previous post) would it require the expansion dev to actually update and provide these infos.
For expansions and plugins that are abandoned, as you pointed out, would this change bring absolutely nothing. You'd still have an expansion with outdated placeholder info.

And finally, the wiki is updated as necessary and as stated on the Placeholders page are we not responsible for it to be up-to-date. It's up to the expansion dev to request updates, either by asking us and providing the necessary info, or by making a Pull request themself.
We legit have other things to do in life that are of much higher importance than checking expansions for if they are up to date or not.

**Comment by TeQTabanca** [comment]
> Please read again what I've written as you clearly ignored the majority of my points.
> 
> We can add a command. That wouldn't be the problem. The problem is where to get the necessary data from.
> 
> PlaceholderAPI doesn't have any kind of algorithm or similar that can recognize what kind of Placeholder Pattern an expansion has. The fact that the `ecloud placeholders` command works is simply due to the fact that every expansion page has a Placeholders section, which PlaceholderAPI pulls data from.
> 
> Also, if we now would make a command which gets the placeholders from the expansion itself (Through the `getPlaceholders()` method mentioned in my previous post) would it require the expansion dev to actually update and provide these infos. For expansions and plugins that are abandoned, as you pointed out, would this change bring absolutely nothing. You'd still have an expansion with outdated placeholder info.
> 
> And finally, the wiki is updated as necessary and as stated on the Placeholders page are we not responsible for it to be up-to-date. It's up to the expansion dev to request updates, either by asking us and providing the necessary info, or by making a Pull request themself. We legit have other things to do in life that are of much higher importance than checking expansions for if they are up to date or not.

**It would have made more sense if PAPI was made when it first came out, but now it seems a little illogical. Because you say that the algorithm does not exist, there may be problems for plugins that support not updated PAPI. Anyway, don't forget to add this command if you can make the algorithm one day in the future. ✍🏼**

**Comment by PiggyPiglet** [comment]
Andre has answered this one perfectly. PAPI does not know what placeholders an expansion provides, and I don't believe this is functionality that we'll ever add.
