### ISSUE TITLE
Conflict with citizen

### ISSUE THREAD

**Issue by Arrandirs** [PlaceholderAPI/PlaceholderAPI#979]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

The problem is not from placeholder directly, I'm using citizen on my server (the build Citizens-2.0.32-b3118.jar). All my npc take knockback when i'm hitting them. They are not supp to take the knockback. The problem is, each hit, they knockback, for a mmorpg server, is it very big like problem. 

I have discuss with the staff of citizen who see no problem. They send me to the discord to ask help BUT with the same message, i take instant ban without anything said. My friend go on discord to ask why, he take ban too. 

i know the problem come from PlaceholderAPI and Citizens conflict because when i remove it, the npc have the normal attitude.
The support from citizen find nothing.

### Expected Behaviour

I want something is found about the problem i discuss since the last month.

### How to Reproduce

Create an npc
See you can hit them SAME if you remove the knocback.

### `/papi dump` Output

https://paste.helpch.at/ifezerufin

### Console Log

https://paste.helpch.at/izajalosev.makefile

**Comment by iGabyTM** [comment]
I highly doubt that papi is causing this. It doesn't have any listener for entity damage, and I don't see how this would happen. Can you try to remove the expansions and see if the issue still persists?
Also, the reason you are being banned from the Citizens discord is because you are using several leaked plugins :)

**Comment by Andre601** [comment]
I use Citizens and PlaceholderAPI on my Server and there are no knockback issues whatsoever. This issue is most likely caused by a 3rd plugin that changes something when PlaceholderAPI is added. Actually test it on a fresh server with just Citizens and PlaceholderAPI themself. If it works fine, then another plugin causes this.

**Comment by Arrandirs** [comment]
Okey thx for the answer. 
But how can i found the 3rd plugin who will cause the problem ? If i see no errors.

Thx for the answer of the banning but like i said on the spigot page, before banning, it can be nice to communicate the problem. 
which plugins are leaked ? You said there is several plugins. Ok, which ones ? I bought by myself so much of these plugins so i will be happy to know which ones are the premade plugins who are not bought ? 
I will contact my mate to have informations about this information because he have access to my server to and work with me. 

To finish, i'm not banned from citizens discord, it have no sense to ban without communication of which rule is broken. To continue to the same way, ban ip for using potential several plugins, is it not to hard to perma ban someone for something like this ?
